CREATE OR REPLACE PROCEDURE CREATE_TRIGGERS AS
-- PRODUCT
BEGIN
EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER PRODUCT_ID_TRIG
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
:NEW.PRODUCT_ID := PRODUCT_ID_SEQ.nextval;
END;';





-- STORE
EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER STORE_ID_TRIG
BEFORE INSERT ON STORE
FOR EACH ROW
BEGIN
:NEW.STORE_ID := STORE_ID_SEQ.nextval;
END;';




-- STORE_STOCK
EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER STORE_STOCK_ID_TRIG
BEFORE INSERT ON STORE_STOCK
FOR EACH ROW
BEGIN
:NEW.STORE_STOCK_ID := STORE_STOCK_ID_SEQ.nextval;
END;';




-- EMPLOYEE



EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER EMP_ID_TRIG
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
:NEW.EMP_ID := EMP_ID_SEQ.nextval;
END;';




-- CUSTOMER



EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER CUSTOMER_ID_TRIG
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
:NEW.CUSTOMER_ID := CUSTOMER_ID_SEQ.nextval;
END;';




-- PAYMENT_TYPE



EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER PAY_ID_TRIG
BEFORE INSERT ON PAYMENT_TYPE
FOR EACH ROW
BEGIN
:NEW.PAY_ID := PAY_ID_SEQ.nextval;
END;';




-- PAYMENT_DETAILS



EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER PAYMENT_NO_TRIG
BEFORE INSERT ON PAYMENT_DETAILS
FOR EACH ROW
BEGIN
:NEW.PAYMENT_NO := PAYMENT_NO_SEQ.nextval;
END;';




-- INVOICE_ORDER



EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER INVOICE_ID_TRIG
BEFORE INSERT ON INVOICE_ORDER
FOR EACH ROW
BEGIN
:NEW.INVOICE_ID := INVOICE_ID_SEQ.nextval;
END;';




-- INVOICE_ORDER_DETAILS



EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER INVOICE_LINE_ID_TRIG
BEFORE INSERT ON INVOICE_ORDER_DETAILS
FOR EACH ROW
BEGIN
:NEW.INVOICE_LINE_ID := INVOICE_LINE_ID_SEQ.nextval;
END;';




-- RETURN INVOICE



EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER RETURN_INVOICE_TRIG
BEFORE INSERT ON RETURN_INVOICE
FOR EACH ROW
BEGIN
:NEW.REUTRN_INVOICE_ID := RETURN_INVOICE_ID_SEQ.nextval;
END;';



END;
