CREATE OR REPLACE PROCEDURE table_creation AS
table_count number := 0;
BEGIN

SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCT';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE PRODUCT cascade constraints';
END IF;
EXECUTE IMMEDIATE '
CREATE TABLE PRODUCT(
PRODUCT_ID INT NOT NULL PRIMARY KEY,
PRODUCT_CATEGORY_ID NUMBER(4,0),
CATEGORY_NAME VARCHAR2(64),
DESCRIPTION VARCHAR2(64),
PRODUCT_NAME VARCHAR2(64),
PRODUCT_PRICE NUMBER(4,2),
BATCH_NO NUMBER(4,0),
EXPIRY_DATE DATE)';


SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'STORE';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE STORE cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE STORE(
STORE_ID INT primary key NOT NULL,
STORE_NAME VARCHAR2(64 BYTE),
CITY VARCHAR2(64 BYTE),
MGRID NUMBER(4,0))';


SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'STORE_STOCK';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE STORE_STOCK cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE STORE_STOCK(
STORE_ID INT,
PRODUCT_ID	INT,
QTY	NUMBER(3,0),
MOST_RECENT_RESTOCKING_DATE	DATE,
STORE_STOCK_ID	NUMBER(38,0) PRIMARY KEY,
FOREIGN KEY (store_id) REFERENCES store(store_id),
FOREIGN KEY (product_id) REFERENCES product(product_id)
)';


SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'EMPLOYEE';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE cascade constraints';
END IF;
EXECUTE IMMEDIATE '
CREATE TABLE EMPLOYEE(
EMP_ID INT NOT NULL PRIMARY KEY,
STORE_ID INT,
EFNAME VARCHAR2(64),
ELNAME VARCHAR2(64),
DOB DATE,
GENDER VARCHAR2(64),
SSN NUMBER(16),
DESIGNATION VARCHAR2(64),
SAL NUMBER(7,2),
ADDRESS VARCHAR2(64),
CITY VARCHAR2(64),
STATE VARCHAR2(64),
ZIP_CODE NUMBER(5,0),
constraints fk_store_id foreign key(store_id) references store)';


SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOMER';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE CUSTOMER(
CUSTOMER_ID INT primary key NOT NULL,
CUSTOMERFNAME VARCHAR2(64),
CUSTOMERLNAME VARCHAR2(64),
DOB DATE,
GENDER VARCHAR2(24),
MOBILE NUMBER(11,0),
STREET VARCHAR2(64),
CITY VARCHAR2(64),
STATE VARCHAR2(20),
ZIP_CODE NUMBER(6,0),
EMAIL VARCHAR2(64))';

SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'PAYMENT_TYPE';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE PAYMENT_TYPE cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE PAYMENT_TYPE(
PAY_ID INT NOT NULL PRIMARY KEY,
PAY_ID_NAME VARCHAR2(64),
PAY_TYPE_NAME VARCHAR2(64))';



SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'INVOICE_ORDER';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE INVOICE_ORDER cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE INVOICE_ORDER(
INVOICE_ID INT NOT NULL PRIMARY KEY,
CUSTOMER_ID INT,
STORE_ID INT,
EMP_ID INT,
TAX NUMBER(4,2),
SALE_AMT NUMBER(5,2),
ORDER_DATE DATE,
RETURN_FLAG VARCHAR2(5),
constraints fk_CUST_ID foreign key(CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID),
constraints fk1_STORE_ID foreign key(STORE_ID) references STORE(STORE_ID),
constraints fk2_EMP_ID foreign key(EMP_ID) references EMPLOYEE(EMP_ID))';


SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'INVOICE_ORDER_DETAILS';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE INVOICE_ORDER_DETAILS cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE INVOICE_ORDER_DETAILS(
INVOICE_LINE_ID	INT PRIMARY KEY,
INVOICE_ID	INT,
PRODUCT_ID	INT,
UNIT_PRICE	NUMBER(4,2),
QUANTITY	NUMBER(4,0),
constraints fk1_INV_ID foreign key(INVOICE_ID) references INVOICE_ORDER(INVOICE_ID),
constraints fk_PROD_ID foreign key(PRODUCT_ID) references PRODUCT(PRODUCT_ID))';


SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'PAYMENT_DETAILS';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE PAYMENT_DETAILS cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE PAYMENT_DETAILS(
PAYMENT_NO INT PRIMARY KEY NOT NULL,
PAY_ID INT,
INVOICE_ID INT,
CARD_NO NUMBER(16,0),
CCEXPIRY_DATE DATE,
CHEQUE_NO NUMBER(16,0),
TRANSACTION_AMOUNT NUMBER(5,2),
constraints fk1_INVOICE_ID foreign key(INVOICE_ID) references INVOICE_ORDER(INVOICE_ID),
constraints fk_PAY_ID foreign key(PAY_ID) references PAYMENT_TYPE(PAY_ID))';

SELECT count(*) INTO table_count FROM USER_TABLES WHERE TABLE_NAME = 'RETURN_INVOICE';
IF table_count != 0 THEN
EXECUTE IMMEDIATE 'DROP TABLE RETURN_INVOICE cascade constraints';
END IF;
EXECUTE IMMEDIATE 'CREATE TABLE RETURN_INVOICE(
REUTRN_INVOICE_ID INT PRIMARY KEY,
INVOICE_ID INT,
RETURN_DATE DATE,
RETURN_AMT NUMBER(6,2),
constraints fk2_INV_ID foreign key(INVOICE_ID) references INVOICE_ORDER(INVOICE_ID))';

END;

