CREATE OR REPLACE PROCEDURE CREATE_TRIG_TO_FILL_STOCK AS
BEGIN
EXECUTE IMMEDIATE '
CREATE OR REPLACE TRIGGER FILL_STOCK
AFTER INSERT ON STORE
FOR EACH ROW
DECLARE
STORE_DATE STORE_STOCK.MOST_RECENT_RESTOCKING_DATE%TYPE;
SID STORE.STORE_ID%TYPE;
BEGIN
SELECT SYSDATE INTO STORE_DATE FROM DUAL;
SELECT MAX(STORE_ID) INTO SID FROM STORE;
INSERT INTO STORE_STOCK(STORE_ID, PRODUCT_ID, QTY, MOST_RECENT_RESTOCKING_DATE) SELECT SID, PRODUCT.PRODUCT_ID, 100, STORE_DATE FROM PRODUCT;
END;'
END;